global:
  resolve_timeout: 1m

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#monitoring'
        send_resolved: true 